[tool.poetry]
name = "codewhispererplayground"
version = "0.1.0"
description = ""
authors = ["Dirk Gómez <dirk@dirkgomez.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.26.37"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
